### ISSUE TITLE
[RPi3] Unable to compile f823abb

### ISSUE THREAD

**Issue by LodanZark** [libretro/mame2003-libretro#327]
Unable to compile the commit f823abb on raspberry pi 3, log:
[rps_2018-03-04_162423.zip](https://github.com/libretro/mame2003-libretro/files/1778699/rps_2018-03-04_162423.zip)

**Comment by markwkidd** [comment]
Thank you for the log, that's very helpful.

I have incorporated a fix for this into this PR: https://github.com/libretro/mame2003-libretro/pull/326

Once / if it is merged, that should fix your issue once you recompile from source.

**Comment by markwkidd** [comment]
@LodanZark the new patch has been merged. can you try to compile mame2003 from source again to make sure that your issue has been resolved?

**Comment by LodanZark** [comment]
Still having problems to compile, here it's the newest log: 
[rps_2018-03-06_171218.log.gz](https://github.com/libretro/mame2003-libretro/files/1786038/rps_2018-03-06_171218.log.gz)

**Comment by markwkidd** [comment]
The last 10 lines of the log suggest that the compiler is trying to build the Windows version and failing. I'm by no means a Makefile expert but this seems odd in part because the same Makefile is building for all the libretro buildbot platforms.

How are you compiling mame2003? Is it within the RetroPie-Setup script?

We may need to tap someone with retropie expertise to help troubleshoot, or possibly someone with Makefile expertise depending on where exactly the issue lies.

**Comment by LodanZark** [comment]
Yes I am using the latest RetroPie-Setup script

**Comment by markwkidd** [comment]
@LodanZark thanks.

@joolswills I apologize for calling on you over here in this repo, but do you see any reason why my recent updates to mame2003 would lead to RetroPie-Setup executing the Makefile's Windows codepath instead of Linux/ARM?

**Comment by joolswills** [comment]
It's broken on Ubuntu Linux on x86_64 also. Not bisected it yet.

**Comment by joolswills** [comment]
bisected to 0ea5c9c7a25371121712bfcbc62d86269667713d

Looks like the trailing whitespace is doing it after `unix`

```
diff --git a/Makefile b/Makefile
index 09e3ce6..92283ff 100644
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,7 @@ endif
 
 ifeq ($(platform),)
 	system_platform = unix
-	platform = unix   
+	platform = unix
 ifeq ($(shell uname -a),)
 	system_platform = win
 	platform = win
```

**Comment by markwkidd** [comment]
Well dangit. I was hoping it wasn't me, but.

It's compiling ok here on linux x64_86 but maybe this `make` is more tolerant. I'll submit a PR right away and edit in the link

**Comment by joolswills** [comment]
https://github.com/libretro/mame2003-libretro/pull/329

**Comment by markwkidd** [comment]
Oh and as I wrote that your link appears

**Comment by markwkidd** [comment]
Thank you

**Comment by joolswills** [comment]
Affect gnu make - it's mentioned in the manual

https://www.gnu.org/software/make/manual/make.html#Flavors

>Since trailing space characters are not stripped from variable values, just a space at the end of the line would have the same effect (but be rather hard to read).

**Comment by joolswills** [comment]
Also - some of your indentation doesn't seem to match the origin file indentations. Not only yours but some previous commits too. the original sources use tab indentation, not spaces. I would think it would be cleaner to stick to the original sources indentation.

**Comment by markwkidd** [comment]
Whoa. OK I knew that make takes spaces seriously but that's a new level in my experience -- just getting used to make here. I've mostly been paranoid about spaces and tabs before commands but I'll start watching for spaces afterward too.

I can't really imagine anything other than fat-finger error causing this, either. 8-)

**Comment by markwkidd** [comment]
> Also - some of your indentation doesn't seem to match the origin file indentations. Not only yours but some previous commits too. the original sources use tab indentation, not spaces. I would think it would be cleaner to stick to the original sources indentation.

I had a conversation with Twinaphex a few days ago about mame2010 and he clarified that he was open to people (me in this case) judiciously standardizing style along with my commits. I'll try to be consistent myself, doing things C-style as he prefers, but I'll also look for opportunities to clean things up.

**Comment by joolswills** [comment]
Well, whether indentation is tabs or spaces etc, it looks ugly when a single source file has mixed tabs and spaces and won't line up nicely (unless your editor happens to have the same tab indent)

**Comment by joolswills** [comment]
I personally tend to stick to the original indentation of the project I'm working on. I prefer space indentation, but for example with ES, it uses tabs, so I use tabs for my additions.

**Comment by markwkidd** [comment]
I'm getting back to coding after years with only some scripting and admin work.

I thought I was reasonably on top of the indent style issue but I probably need to get into a real IDE or double down on Notepad++ (my current editor of choice) so that it's easier for me to be on top of this.

I'm honestly guilty of occasionally throwing a quick code idea down into my development branch via the github web editor. I suspect that may have been how some of this crept in. I've learned git to work on libretro stuff and I' getting pretty competent. I just need to pretend the github web editor doesn't exist.

**Comment by markwkidd** [comment]
@LodanZark the patch that joolswills submitted has just been merged. This time, your problem really should be solved!

**Comment by LodanZark** [comment]
@markwkidd it's working now, thanks very much
